# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.4
env:
  - GROUP=convergence
  - GROUP=torques
  - GROUP=ellipticity
  - GROUP=lehnert
  - GROUP=dense_amom
  - GROUP=dense_sphere
  - GROUP=malkus
notifications:
  email: false
addons:
  apt:
    packages:
      - texlive
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-pictures
      - texlive-fonts-recommended
      - texlive-latex-extra
      - dvipng
      - ghostscript-x
      - python3-pip
install:
  - pip3 install --user --upgrade pip setuptools
  - pip3 install matplotlib
  - pip3 install --upgrade matplotlib
# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.2
#       os:
#           - linux
#           - osx
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
#           Pkg.add(PackageSpec(url="https://github.com/fgerick/Mire.jl.git"));
#                                                Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
