# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.4
notifications:
  email: false
addons:
  apt:
    packages:
      - texlive-full
      - python3-pip
      - python-pip
install:
  - pip install --user --upgrade pip setuptools
  - pip3 install --user --upgrade pip setuptools
  - pip3 install matplotlib
  - pip3 install --upgrade matplotlib
  - pip install matplotlib
  - pip install --upgrade matplotlib
# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.2
#       os:
#           - linux
#           - osx
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
#           Pkg.add(PackageSpec(url="https://github.com/fgerick/Mire.jl.git"));
#                                                Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
