# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.2
matrix:
  fast_finish: true
notifications:
  email: false
jobs:
  include:
    - stage: Documentation
      julia: 1.2
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(PackageSpec(url="https://github.com/fgerick/Mire.jl.git"));
          Pkg.add(PackageSpec(url="https://github.com/fgerick/Elltorque.jl.git"));
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
