# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.3
notifications:
  email: false
addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.2
#       os:
#           - linux
#           - osx
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
#           Pkg.add(PackageSpec(url="https://github.com/fgerick/Mire.jl.git"));
#                                                Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
